### ISSUE TITLE
Support reviver as in JSON.parse()?

### ISSUE THREAD

**Issue by coodoo** [laktak/hjson-js#11]
Just wondering is reviver support on the roadmap, see [details here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Using_the_reviver_parameter).

Since `hjson` makes it easy to write multi line strings it seems to be a perfect match to write functions in `hjson` as string and later restore it back to function when parsing, thought?

**Comment by laktak** [comment]
I don't see the advantage over parsing the data first and traversing the output afterwards.
