### ISSUE TITLE
Regression: hjson.parse returns non null/json result in 1.8.4

### ISSUE THREAD

**Issue by crunchie84** [laktak/hjson-js#12]
We have recently updated hjson from 1.7.4 to 1.8.4 and found a regression:

```javascript
const result = hjson.parse('totally invalid JSON');
console.log(result, typeof result); //emits 'totally invalid JSON string'
```

The behaviour using 1.7.4 was that this string yielded `null` as expected since this is not in any way json-ish.

**Comment by laktak** [comment]
`totally invalid JSON` is actually a quoteless Hjson string. I agree though that this is probably unexpected  - I'll look into it for a fix.

**Comment by laktak** [comment]
Sorry, there is already a testcase that explicitly allows this (https://github.com/laktak/hjson/blob/master/testCases/passSingle_test.hjson)
