### ISSUE TITLE
Highlight differences with YAML

### ISSUE THREAD

**Issue by flesler** [laktak/hjson-js#3]
HI

I think it'd be useful if you'd add a README section where visitors can quickly see the differences of Hjson to YAML, that serves a similar purpose and shares several features.

**Comment by laktak** [comment]
Since this has come up before I've added a short section at [hjson.org](http://hjson.org/#yaml).

Was this what you had in mind?

**Comment by flesler** [comment]
Well, yes. A more descriptive set of differences would be nicer though.

**Comment by laktak** [comment]
You probably know YAML a lot better than I do. Would you mind creating a wiki page? https://github.com/laktak/hjson/wiki/Yaml

**Comment by flesler** [comment]
I actually don't know much, was looking for a good format to use and found both.
