### ISSUE TITLE
Quotes in arrays shouldn't be required?

### ISSUE THREAD

**Issue by ivanceras** [laktak/hjson-js#6]
Seems the double quote in arrays are strictly required while key value are loosely allowed to quote or not. There seems to be a discrepancy in the format. 

```
{
    display_name: Products,
    identifier: [name, description], ## Without quotes does NOT work
    order: ['name', 'description', 'active], ## Single quotes does NOT work as well
    hide: ["createdby", "created", "updatedby","updated"] ##Double quotes works, no problem
    
}
```

**Comment by laktak** [comment]
Actually they work just fine in arrays:

```
{
  display_name: Products
  identifier: [
    name
    description
  ]
}
```

> Remember that quoteless strings include everything up to the end of the line

So you need to put each value on its own line.
