### ISSUE TITLE
Could/should the following be valid for hjson?  { 'a' : 'b' }

### ISSUE THREAD

**Issue by gitgrimbo** [laktak/hjson-js#7]
Hi,

Could/should the following be valid for hjson?

`{ 'a' : 'b' }`

The error is:

`Error: Found ' ' where a key name was expected (check your syntax or use quotes if the key name includes {}[],: or whitespace) at line 1,5 >>> 'a' : 'b' } ...`

The following is valid (both the newline and the removal of the space before the colon seem necessary):

```
{ 'a': 'b'
}
````

and produces this output:

````
{
  "'a'": "'b'"
}
````

but I would like it to produce the following object:

`{ a : 'b' }`

**Comment by laktak** [comment]
You can either use double quotes (`"`) or no quotes to define a string. Single quotes (`'`) are not supported.

e.g.

```
{ a: "b" }
```
or

```
{
  a: b
}
```
