### ISSUE TITLE
include a require hook

### ISSUE THREAD

**Issue by seiyria** [laktak/hjson-js#8]
Having a require hook would be great - the boilerplate required to load a file with hjson would be significantly lessened.

**Comment by laktak** [comment]
You want to do something like `var config=require("./config.hjson");`?

```
var fs=require("fs");
var Hjson=require("hjson");

require.extensions[".hjson"]=function(module, filename) {
  var content=fs.readFileSync(filename, "utf8");
  module.exports=Hjson.parse(content);
};
```

**Comment by seiyria** [comment]
Yup, that's exactly what I want. I was hoping it'd be something that could be built in, but if not, this is fine too.

**Comment by laktak** [comment]
Shouldn't be a problem though it will take a few days before I can get around to it.

**Comment by ehmicky** [comment]
Note that `require.extensions` is [deprecated](https://nodejs.org/api/globals.html#globals_require_extensions)
